services:
  postgres:
    container_name: postgres-sql-taskpro
    image: postgres
    environment:
      POSTGRES_USER: taskpro
      POSTGRES_PASSWORD: taskpro
      POSTGRES_DB: taskprodb
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-taskpro
    image: maildev/maildev
    ports:
      - "1080:1080"  # Web UI (http://localhost:1080)
      - "1025:1025"  # SMTP
    networks:
      - spring-demo
    restart: unless-stopped

  backend:
    container_name: taskpro-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:postgresql://postgres-sql-taskpro:5432/taskprodb
      DB_USERNAME: taskpro
      DB_PASSWORD: taskpro
      MAIL_HOST: mail-dev-taskpro
      MAIL_PORT: 1025
      MAIL_USERNAME: taskpro
      MAIL_PASSWORD: taskpro
      JWT_SECRET_KEY: wPGNMJ/Vag6i23vF7Dc4la3y8IHirOpmoOQ5jZnbepI=
      JWT_EXPIRATION: 86400000
      FILE_UPLOAD_PATH: /app/uploads
    volumes:
      - uploads:/app/uploads
    depends_on:
      - postgres
      - mail-dev
    networks:
      - spring-demo
    restart: unless-stopped

volumes:
  postgres:
    driver: local
  uploads:
    driver: local

networks:
  spring-demo:
    driver: bridge
