services:
  postgres:
    container_name: postgres-sql-taskpro
    image: postgres
    environment:
      POSTGRES_USER: taskpro
      POSTGRES_PASSWORD: taskpro
      POSTGRES_DB: taskprodb
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-taskpro
    image: maildev/maildev
    ports:
      - "1080:1080"  # Web UI (http://localhost:1080)
      - "1025:1025"  # SMTP
    networks:
      - spring-demo
    restart: unless-stopped

volumes:
  postgres:
    driver: local

networks:
  spring-demo:
    driver: bridge
