# --- DATABASE CONFIG ---
spring.datasource.url=jdbc:h2:mem:taskprodb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

# --- JPA CONFIG ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# --- H2 Console ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- Server Port (optionnel) ---
server.port=8081

logging.level.org.springframework.security=DEBUG
application.security.jwt.secret-key=wPGNMJ/Vag6i23vF7Dc4la3y8IHirOpmoOQ5jZnbepI=
application.security.jwt.expiration=86400000 

